### PR TITLE
Mapping some keys

### PR DESCRIPTION
**Pull request by franklinjavier**
I usually use shortcut keys everywhere. So I would suggest that.

J - next song
K - prev song
Space - play/pause song
/ - Focus in search field

### CODE REVIEW

**Comment by andrewngu** [comment]
Sweet! I really like this feature. One small thing, should we move the the anonymous function to a named function, that way we can easily unbind during the componentWillUnmount hook? Similar to https://github.com/andrewngu/sound-redux/blob/master/scripts/components/InfiniteScrollify.js

**Comment by franklinjavier** [comment]
Indeed :+1:

**Comment by andrewngu** [comment]
deployed :smile:

**Comment by franklinjavier** [comment]
Thanks a lot mate :beers:

**Pull request merged**
