### PR TITLE
added arrow keys for next and previous track

### PR DESCRIPTION
**Pull request by ghondar**
shall be the arrows right and left to change to the next music or previous music respectively

### CODE REVIEW

**Comment by andrewngu** [comment]
Looks good, can we move the keypress event handler into the keydown handler, so that we're only binding a single keyboard handler?

**Comment by ghondar** [comment]
keypress has 37 and 39 keycode in other keys, I had to put a conditional

**Comment by ghondar** [comment]
you're right :)

**Comment by andrewngu** [comment]
Beautiful, thanks for your work on this :+1:

**Pull request merged**
