### PR TITLE
title attribute added

### PR DESCRIPTION
**Pull request by ghondar**
-attribute title added on a tag for a better view of texts

### CODE REVIEW

**Comment by andrewngu** [comment]
Hmmm, not too keen on this because I think the tool tip is distracting and it doesn't do anything to help accessibility.

**Comment by ghondar** [comment]
of course, but I think when a music that we like and want to know the name of it; have no way of knowing the full name, we would have to search the entire list, making it tedious to find the green card if previously played several songs.

**Comment by andrewngu** [comment]
Ahhh, yeah, you are right. How about we just add this to just song titles for now?

**Comment by ghondar** [comment]
maybe using title props on Link component

**Comment by andrewngu** [comment]
Yah, exactly what I was thinking

**Comment by andrewngu** [comment]
@ghondar this has been fixed and deployed :smile:

**Comment by andrewngu** [comment]
Oh sorry, I didn't see your latest commit :point_up:

**Comment by ghondar** [comment]
:smile:

**Comment by andrewngu** [comment]
deployed, thanks! :+1:

**Pull request merged**
